# Runs Bazel tests for DeepMind Lab

sudo: true

language: c++

dist: xenial

compiler:
  - clang
  - gcc

addons:
  apt:
    sources:
      - webupd8team-java
      - sourceline: 'deb [arch=amd64] http://storage.googleapis.com/bazel-apt stable jdk1.8'
        key_url: 'https://bazel.build/bazel-release.pub.gpg'
    packages:
      - libffi-dev
      - gettext
      - freeglut3-dev
      - libsdl2-dev
      - libosmesa6-dev
      - python-dev
      - python-numpy
      - python-pil
      - python3-dev
      - python3-numpy
      - python3-pil

before_install:
  - echo debconf shared/accepted-oracle-license-v1-1 select true | sudo debconf-set-selections
  - echo debconf shared/accepted-oracle-license-v1-1 seen true | sudo debconf-set-selections
  - sudo apt-get install bazel

script:
  - case "${CXX}" in
      "g++")     bazel test --show_progress_rate_limit=20 --test_output=errors -c opt --copt=-Wno-sign-compare --copt=-Wno-maybe-uninitialized //... ;;
      "clang++") bazel test --show_progress_rate_limit=20 --test_output=errors -c opt --copt=-Wno-sign-compare --copt=-Wno-uninitialized --cxxopt=-std=c++11 //... ;;
    esac
